services:
  backend:
    image: shawnjensen/devops-group-c-fall2025-backend:latest
    ports:
      - "5000:5000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=5000
      - HOST=0.0.0.0

  frontend:
    image: shawnjensen/devops-group-c-fall2025-frontend:latest
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - backend